language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

# "secure:" is for encrypted GITHUB_COMPOSER_AUTH ((o be able to use composer without GitHub API limits)
env:
  secure: k0jrQOB4M4BRCgj7y4VlBtVu9SN8SoJPjEucalIhijwLsG4yObPhLlGeyut3NARM1YHnpNS61cGuSZ4IiMDYIcgApimOe1W9tk4HVbkndFfnCT/lWfxV9CQaliP7s9bprbIcYJuJCeVEzblFwkL573A9gBZjNKUIFi7fn1damZWH0VHmRYwi9NnQwr7bSt57StElD+akgSZDbNWjL0fFeHxjHPvoVsw6P2QofTctCbdqwjM29l8sxRcoaNWohAj9gB7dJQDRmpKY0jO4DP+qeYC0wJbPvS0Hd7B7HdoH5LooYOwcnIuof+rysDf5JUXYwuY6WBMV2ZMAdrFXuY5k8P/S/gSIkZRcmJwOPwvNEkF7ne1llhg3+lsMVU17IEL6TCzoDAf5/ulpLsxhm8/wTwezh/cfLBURw0T4h1EBl45bubt5ivLDFSMhAeMBGUSSK9lSP+gcI5xpRokTbkTok019aDgA4b/Wq/S3lu2yV0Um9X9sgxJI1zVu7vfr+9uTZMbsORCAx/H38P0cwpxNg+tCr+uIT6LUEjq1kg81ion95fuGVtdDy/LIfvDXNxcgQCk+pAAY9Mrfx98djdPy5KE5MT8d4xt33TRBUIuZyeU5tK49R8leasSUYE2eOdc70/NdRWR32d2mNW0sDl5MTCUKZrzjljck/4h/nMUlI4U=
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - CC_TEST_REPORTER_ID=2f4620ac239cc7fdb27b299c24422281b04fd8012820ba173e92c70953385958
  matrix:
    - COMPOSER_FLAGS=--prefer-lowest
    - COMPOSER_FLAGS=

# php-vcr 1.3 (--prefer-lowest) uses Symfony\Components\EventDispatcher\Event and is compatible for Laravel < 7  and PHP < 7.4
# php-vcr 1.4.4.4 (latest)      uses Symfony\Contracts\EventDispatcher\Event  and is compatible for Laravel >= 7 and PHP >= 7.1
# => PHP 7.4 cannot work with --prefer-lowest and resolve these contraints (only used for test environment in 'require-dev', no impact in production)
matrix:
  exclude:
    - php: 7.4
      env: COMPOSER_FLAGS=--prefer-lowest # php-vcr 1.3 is needed for lowest (for Symfony\Component\EventDispatcher\Event), 1.4.4.4 for normal, but 1.3 is incompatible with PHP 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - travis_wait composer update --no-interaction --prefer-stable $COMPOSER_FLAGS
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  email:
    recipients:
      - contact@translation.io
